### ISSUE TITLE
[Bug] Disabling a preset doesn't work if its in the process of fading / lerping in

### ISSUE THREAD

**Issue by 3ti65** [BF3RM/VEManager#1]
As the title reads, if you disable a preset, it doesnt effect the fading in and probably fading out process.

**Comment by IllustrisJack** [comment]
gonna check if stuck ve´s is due to this

**Comment by IllustrisJack** [comment]
https://github.com/BF3RM/VEManager/commit/91fa2b4186bd778355820585c445a14fe5f7ac47 trying this first

**Comment by GreatApo** [comment]
@IllustrisJack this was a problem from RM side. I fixed it in the past

**Comment by IllustrisJack** [comment]
@GreatApo Good 2 Know, thanks for the heads up! welp - then back to investigating I guess. https://github.com/BF3RM/RealityMod/issues/529 is annoying ... - any ideas?
