### ISSUE TITLE
[Bug] Skybox and other CtrRefs are fucked up

### ISSUE THREAD

**Issue by 3ti65** [BF3RM/VEManager#2]
Blue Skybox, black skybox, etc.

The serialization of CtrRefs (instances) is as follows right now:

`"ColorGradingTexture": "sol.sol::detail::unique_usertype<VeniceEXT::Classes::Shared::DataContainer>: 40E3F4F0"`

Saving this as a string is obviously retarded. We have to not overwrite these values or implement a proper serialization. If we do a proper serialization, the type should be the one required by the component referencing it, and not just datacontainer.

**Comment by 3ti65** [comment]
Since this is a serialization issue, it also effects the CT part of it.

**Comment by Powback** [comment]
This is a Cinetools issue though.

**Comment by 3ti65** [comment]
Yeah, but if we enable proper serialization of those CtrRefs within CT / MapEditor, then we have to handle it on VEManager side as well.
